# -*- coding: utf-8 -*-
"""CO2 emissions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_dcrwkawQywKQ6-fDQ3WDbFBsvRCpNP
"""



pip install dash

import pandas as pd

import plotly.express as px

df= pd.read_excel("co2barchart.xlsx")

df

fig2= px.bar(df, x='Continent ', y='Total Co2 emissions', color='Year', barmode='group',
             labels={'Year': 'Year', 'Total Co2 emissions': 'Total Co2 emissions', 'Year': 'Year'}
             )
fig2.show()

fig_co2bar= px.bar(df, x='Continent ', y='Total Co2 emissions', color='Year', barmode='group',
             labels={'Year': 'Year', 'Total Co2 emissions': 'Total Co2 emissions', 'Year': 'Year'}
             )

fig_co2bar.show()

from dash import Dash, html, dash_table, dcc

app = Dash(__name__)

fig_co2bar= px.bar(df, x='Continent ', y='Total Co2 emissions', color='Year', barmode='group',
             labels={'Year': 'Year', 'Total Co2 emissions': 'Total Co2 emissions', 'Year': 'Year'}
             )



# App layout
app.layout = html.Div([
    html.Div([
        html.H1("Figure 3"),
        dcc.Graph(figure=fig_co2bar)
            ])
])

# Run the app
if __name__ == '__main__':
    app.run(debug=True)